(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount)) balance)
      "Insufficient funds")
  )
  (define (deposit amount)
    (begin (set! balance (+ balance amount)) balance)
  )
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknow request: MAKE-ACCOUTN" m))
    )
  )
  dispatch
)
(define acc1 (make-account 220))