(load "Exercise3-3.scm")
(define (make-joint main-acc main-pwd second-pwd)
  (let ((wrong-times 0))
  ; (define (withdraw amount)
  ;   (if (>= balance amount)
  ;     (begin (set! balance (- balance amount)) balance)
  ;     "Insufficient funds")
  ; )
  ; (define (deposit amount)
  ;   (begin (set! balance (+ balance amount)) balance)
  ; )
  (define (wrong-pwd)
    (if (> wrong-times 7)
        (error "call-the-cops")
        (error "Incorrect-password")
    )
  )
  (define (dispatch password m)
    (cond ((eq? password second-pwd)
            (set! wrong-times 0)
            (cond ((eq? m 'withdraw) (main-acc main-pwd 'withdraw))
                ((eq? m 'deposit) (main-acc main-pwd 'deposit))
                (else (error "Unknow request: MAKE-ACCOUTN" m))
            )
          )
        (else
          (set! wrong-times (+ wrong-times 1))
          (wrong-pwd)
        )
    )
  )
  dispatch
  )
)
