(define (make-monitored f)
  (let ((count 0))
    (define (how-many-calls?)
      (begin count)
    )
    (define (reset-count)
      (begin (set! count 0) count)
    )
    (define (run-func arg)
      (begin (set! count (+ count 1)) (f arg))
    )
    (define (dispatch m)
      (cond ((eq? m 'how-many-calls?) (how-many-calls?))
            ((eq? m 'reset-count) (reset-count))
            (else (run-func m))
      )
    )
    dispatch
  )
)